name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      deployApp:
        description: 'Build and push App-Image'
        required: false
        default: true
        type: boolean
      deployNginx:
        description: 'Build and push Nginx-Image'
        required: false
        default: false
        type: boolean
  # push:
  #   branches:
  #     - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push App-Image
        if: ${{ inputs.deployApp }} == true
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: krompi/laravel-base-app:latest
          file: Dockerfile-app-latest

      - name: Build and push Nginx-Image
        if: ${{ inputs.deployNginx }} == true
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: krompi/laravel-base-nginx:latest
          file: Dockerfile-nginx
